#!/usr/bin/env bash
#tell the story of passwd
while read -r username password userid groupid user_info home_directory command_shell; do
    echo "The user $username is part of the $groupid gang, lives in $home_directory, and rides $command_shell."
    echo "USER ID's place is protected by the passcode $password, more info about the user here: $user_info"
    echo  # Add a blank line for separation
done < /etc/passwd
