#!/usr/bin/env bash
#using a while loop to display "Best School" ten times, but Hi on the ninth line
i=1
while [ $i -le 10 ]
do
if [ $i -eq 9 ]
then
echo -e "Best School\nHi"
else
echo "Best School"
fi
i=$((i+1))
done
