#!/usr/bin/env bash
#An if, else loop
filename="School"
if [ -e "$filename" ]
then
echo "school file exists"
if [ -s "$filename" ]
then
echo "School filee is not empty"
else
echo "school file is empty"
fi
if [ -f "$filename" ]
then
echo "School is a regular file"
fi
else
echo "School file does not exist"
fi
